# Generated by Django 5.2.8 on 2025-12-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
